In [1]:
import numpy as np

In [2]:
array = np.array([2,3,4,5,6])
type(array)

numpy.ndarray

# ndim : to check the dimensions of an array

In [3]:
array = np.array([[2,3,4,5,6]])
array.ndim

2

In [4]:
array = np.array([[[2,3],
                   [5,6]],
                  [[1,1],
                   [1,1]]])
array.ndim

3

In [5]:
array = np.array([[[2,3],[5,6]],[[1,1],[1,1]]])
array.ndim

3

In [6]:
array = np.array(2.3)  # 0 diemnsion array.
array.ndim

0

# ndmin : converting lower dimensions into higher dimensions

In [7]:
array = np.array(2.3,ndmin=3)  # 0 dimesion array converted into 3 diemsion array
print(array)
array.ndim

[[[2.3]]]


3

In [8]:
array = np.array([[[2,3],[3,4]]],ndmin=1)    # 3 dimension array cannot be conveted into 1 dimension array.
print(array) 
array.ndim

[[[2 3]
  [3 4]]]


3

# np.array() array constructor.

In [9]:
import numpy as np

In [10]:
# converting list to array

l1=[2,3,4]
arr=np.array(l1)
print(arr)
type(arr)

[2 3 4]


numpy.ndarray

In [11]:
# tuple to array

t1=(2,3,4)                # t1 = 2,3,4 if no bracket is given by default it is in tuple format. 
arr=np.array(t1)
print(arr)
type(arr)

[2 3 4]


numpy.ndarray

In [12]:
# set to array

set_1 = {2,3,4,4}
a = np.array(set_1)
print(a)
type(a)

{2, 3, 4}


numpy.ndarray

In [13]:
# dictionary to array

d1={'bhushan':23 , 'college': 'ambedkar'}
a = np.array(d1)
print(a)
type(a)

{'bhushan': 23, 'college': 'ambedkar'}


numpy.ndarray

In [14]:
# string to array

s='pratiksha'
a= np.array(s)
print(a)
type(a)

pratiksha


numpy.ndarray

#  why is numpy called as homogeneous data type

In [15]:
array = np.array([2,3.0,5])    # all converted to float.
print(array)

[2. 3. 5.]


In [16]:
array = np.array([2,3,5])
print(array)

[2 3 5]


In [17]:
array = np.array([2,3.0,3+4j])   # all items converted to complex numbers.
print(array)

[2.+0.j 3.+0.j 3.+4.j]


In [18]:
array = np.array([2,3.0,3+4j,'3.5']) # all converted to string
print(array)

['2' '3.0' '(3+4j)' '3.5']


# dtype : Assigning a single data type to an entire array

In [19]:
array = np.array([2.0,3,4.8],dtype='int')
print(array)
array

[2 3 4]


array([2, 3, 4])

In [20]:
arr = np.array([2,3,4.8],dtype='complex')
print(arr)

[2. +0.j 3. +0.j 4.8+0.j]


In [21]:
arr = np.array([2,3,4+3j],dtype='str')
print(arr)

['2' '3' '(4+3j)']


In [22]:
# by using object as datatype , datatypes of each individual item is preserved.

a = np.array([2,3.5,4+8j,'6'],dtype='object')
print(a)
print(type(a[0]))       
print(type(a[1]))
print(type(a[2]))
print(type(a[3]))

[2 3.5 (4+8j) '6']
<class 'int'>
<class 'float'>
<class 'complex'>
<class 'str'>


## pandas

In [23]:
import pandas as pd

In [24]:
a=np.array([2,3.5,4+8j])
df = pd.DataFrame(a,columns=['data types'])
df

data types
0    2.0+0.0j
1    3.5+0.0j
2    4.0+8.0j

In [25]:
a=np.array([2,3.5,4+8j],dtype='object')
df = pd.DataFrame(a,columns=['data types'])
df

data types
0          2
1        3.5
2     (4+8j)

In [31]:
l1 = [2,3.5,4,5]

df = pd.DataFrame(l1)
display(df)
df.info()

0
0  2.0
1  3.5
2  4.0
3  5.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       4 non-null      float64
dtypes: float64(1)
memory usage: 164.0 bytes


In [32]:
df = df + 2
df

0
0  4.0
1  5.5
2  6.0
3  7.0

In [36]:
l1 = [2,3,4,'5']

df1 = pd.DataFrame(l1)
display(df1)
df1.info()

0
0  2
1  3
2  4
3  5

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       4 non-null      object
dtypes: object(1)
memory usage: 164.0+ bytes


In [34]:
df1 = df1+2 # 5 is string type in l1 .
 df1          # evenif there is single item of datatype string in given array then we cannot perform artithmatic operations.

TypeError: can only concatenate str (not "int") to str

# indexing

In [37]:
import numpy as np

In [38]:
array = np.array([[2,3,5,6],
                  [5,6,7,8]])
array[1]

array([5, 6, 7, 8])

In [39]:
array[1][2]

7

In [40]:
array = np.array([[[2,3,5,6],
                   [5,6,7,8],
                   [4,5,5,5]],
                  [[8,8,9,0],
                   [1,2,3,1],
                   [2,2,3,1]]])
array[1][2][-2]

3

# slicing

In [41]:
array = np.array([[[2,3,5,6],
                   [5,6,7,8],
                   [4,5,5,5]],
                  [[8,8,9,0],
                   [1,2,3,1],
                   [2,2,3,1]]])
# print(array[1])


array[1][:2,1:3]  

array([[8, 9],
       [2, 3]])

In [42]:
import numpy as np

array = np.array([[[[2,3,5,6],
                    [5,6,7,8],
                    [4,5,5,5]],
                   [[8,8,9,0],
                    [1,2,3,1],
                    [2,2,3,1]]],
                  
                  [[[2,3,5,6],
                    [5,6,7,8],
                    [4,5,5,5]],
                   [[8,8,9,0],
                    [1,2,3,1],
                    [2,2,3,1]]]])

# array[:,:,1:,2:]  
# array[:,:,1:2,2:]
array[:,:1,1:,:2]  

array([[[[5, 6],
         [4, 5]]],


       [[[5, 6],
         [4, 5]]]])

In [43]:
import numpy as np

array = np.array([[[[2,3,5,6],
                    [5,6,7,8],
                    [4,5,5,5]],
                   [[8,8,9,0],
                    [1,2,3,1],
                    [2,2,3,1]]],
                  
                  [[[20,30,50,60],
                    [50,60,70,80],
                    [40,50,50,50]],
                   [[60,80,90,0],
                    [10,20,30,10],
                    [20,20,30,10]]]])

# array[:,:,1:,2:]  
# array[:,:,1:2,2:]
array[:,:1,1:,:2]  

array([[[[ 5,  6],
         [ 4,  5]]],


       [[[50, 60],
         [40, 50]]]])

# Reshape

In [44]:
import numpy as np
Array = np.array([2,3,5,7,8,9,0,1,5,2,7,2])
Array

array([2, 3, 5, 7, 8, 9, 0, 1, 5, 2, 7, 2])

In [47]:
Array.reshape(12,1)
Array.reshape(3,4)
Array.reshape(4,3)
Array.reshape(2,6)
Array.reshape(6,2) # this final is executed.i.e 6 rows and 2 columns.

array([[2, 3],
       [5, 7],
       [8, 9],
       [0, 1],
       [5, 2],
       [7, 2]])

In [48]:
Array.reshape(3,2,2)                 # arr.reshape(no of matrix,rows,column)

array([[[2, 3],
        [5, 7]],

       [[8, 9],
        [0, 1]],

       [[5, 2],
        [7, 2]]])

# converting an array to list

In [52]:
arr = np.array([2,3,5,7,8,9,0,1,5,2,7,2])
X = list(arr)

X.append([100,200])
X

[2, 3, 5, 7, 8, 9, 0, 1, 5, 2, 7, 2, [100, 200]]

In [50]:
arr = np.array([2,4,5,6])
x = arr.tolist()
print(x)

x.extend([100,200])
x

[2, 4, 5, 6]


[2, 4, 5, 6, 100, 200]

In [53]:
import numpy as np

arr = np.array([2,3,4,5])
a = arr.reshape(1,4)
print(a)                    # now arr is converted into 2d array       

x = list(a)                 # 2d array converted into list
print(x)

x.append(100)       # 100 is append at 1st index and x(list) is at 0th index . when we append more than 1d array this happens 
print(x)

[[2 3 4 5]]
[array([2, 3, 4, 5])]
[array([2, 3, 4, 5]), 100]


## I want to add 100 in array list itself

In [54]:
a

array([[2, 3, 4, 5]])

In [55]:
y = list(a[0])
y.append(100)
y.append(200)
print(y)

[2, 3, 4, 5, 100, 200]


## now i want to rehape y , y is in list format to reshape y we need to first convert it into array

In [56]:
import numpy as np
z = np.array(y)
z.reshape(2,3)

array([[  2,   3,   4],
       [  5, 100, 200]])

# Creating an empty array

In [57]:
arr = np.array([])
arr

array([], dtype=float64)

# Creating an array or matrix of zeros

In [58]:
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [59]:
import numpy as np

arr = np.zeros(5,dtype='int')
print(arr)

[0 0 0 0 0]


In [60]:
arr = np.zeros(5,dtype='I')
print(arr)

[0 0 0 0 0]


In [61]:
arr = np.zeros((5,4),dtype='I')
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


# creating a matrix of ones

In [62]:
arr = np.ones((3,4),dtype='I')
print(arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [63]:
import pandas as pd
df = pd.DataFrame(arr,columns=list('ABCD'))
df

A  B  C  D
0  1  1  1  1
1  1  1  1  1
2  1  1  1  1

 # creating a sequence of numbers using arange function

In [64]:
arr = np.arange(1,20)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [65]:
arr=np.arange(1,20,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]


In [66]:
arr=np.arange(20,0,-2,dtype='float').reshape(2,5)
print(arr)

[[20. 18. 16. 14. 12.]
 [10.  8.  6.  4.  2.]]


# linspace() for creating linearly spaced values

In [2]:
import numpy as np

dummy_arr= np.linspace(0,11,num=6,dtype='I',retstep=True)  
print(dummy_arr)

(array([ 0,  2,  4,  6,  8, 11], dtype=uint32), 2.2)


In [3]:
dummy_arr = np.linspace(0,20,20)
print(dummy_arr)

[ 0.          1.05263158  2.10526316  3.15789474  4.21052632  5.26315789
  6.31578947  7.36842105  8.42105263  9.47368421 10.52631579 11.57894737
 12.63157895 13.68421053 14.73684211 15.78947368 16.84210526 17.89473684
 18.94736842 20.        ]


In [72]:
dummy_arr = np.linspace(0,20,11)
print(dummy_arr)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [73]:
dummy_arr = np.linspace(0,20,20)
print(dummy_arr)

[ 0.          1.05263158  2.10526316  3.15789474  4.21052632  5.26315789
  6.31578947  7.36842105  8.42105263  9.47368421 10.52631579 11.57894737
 12.63157895 13.68421053 14.73684211 15.78947368 16.84210526 17.89473684
 18.94736842 20.        ]


# Generating Random numbers


In [6]:
import random
random.random()

0.9733422551938672

##  Random.rand()

In [7]:
some_nums = np.random.rand()
some_nums

0.3570319929881386

In [8]:
some_nums = np.random.rand(5)
some_nums

array([0.84537196, 0.87446203, 0.16358855, 0.24684685, 0.68842028])

In [9]:
some_nums = np.random.rand(2,3)
some_nums

array([[0.55292885, 0.66177441, 0.12865352],
       [0.58680481, 0.3762828 , 0.2505749 ]])

## Random.random()

In [10]:
np.random.random(5)

array([0.9920735 , 0.3756393 , 0.53124474, 0.01011116, 0.00258663])

In [11]:
np.random.random(2,12)

TypeError: random() takes at most 1 positional argument (2 given)

In [12]:
np.random.random(10).reshape(2,5)

array([[0.41335997, 0.1996841 , 0.63461746, 0.92728761, 0.89083767],
       [0.07670332, 0.95652835, 0.56452687, 0.78161257, 0.88580031]])

## random.randn()

In [14]:
np.random.randn(5)

array([-0.53013733,  0.49933597, -0.06235048, -1.16076689, -0.72084176])

In [15]:
np.random.randn(2,2)

array([[-2.06752683,  1.70369246],
       [-1.88218564,  1.42886572]])

## random().randint()

In [18]:
np.random.randint(1,20,10)

array([13,  3,  2,  5, 19, 14,  5,  2,  2, 11])

In [20]:
a= np.random.randint(low=1,high=100,size=15,dtype='I')
print(a)

[80 82 79 72 77 29 19 12 45 40  3  4 37 82 90]


In [22]:
ran_nums = np.random.randint(1,100,25)
ran_nums

array([31, 71, 59, 98, 31, 39, 19, 71, 18, 91, 21,  8, 55,  8, 54, 38,  1,
       41, 89, 31, 37,  6, 56, 73, 48])

## Ascending sort

In [23]:
np.sort(ran_nums)

array([ 1,  6,  8,  8, 18, 19, 21, 31, 31, 31, 37, 38, 39, 41, 48, 54, 55,
       56, 59, 71, 71, 73, 89, 91, 98])

## Descending sort

In [24]:
sorted_ran_nums=sorted(ran_nums,reverse=True)
print(sorted_ran_nums)

[98, 91, 89, 73, 71, 71, 59, 56, 55, 54, 48, 41, 39, 38, 37, 31, 31, 31, 21, 19, 18, 8, 8, 6, 1]


In [25]:
np.sort(ran_nums)[::-1]

array([98, 91, 89, 73, 71, 71, 59, 56, 55, 54, 48, 41, 39, 38, 37, 31, 31,
       31, 21, 19, 18,  8,  8,  6,  1])

In [ ]:
for i in range(len(ran_nums)):
    for j in range(i+1,len(ran_nums)):
        if ran_nums[i]<ran_nums[j]:
            ran_nums[i],ran_nums[j]=ran_nums[j],ran_nums[i]
print(ran_nums)

## sorting of matrix

In [26]:
np.sort([2,3,0])

array([0, 2, 3])

In [27]:
np.sort([2,3,0],axis=-1)  # by default axis is -1. you cannot use axis=1 here

array([0, 2, 3])

### sorting row wise ( axis = 1 or -1 )

In [28]:
np.sort([[2,3,0],
         [7,5,8]],axis=1)

array([[0, 2, 3],
       [5, 7, 8]])

In [29]:
np.sort([[2,3,0],                     
         [7,5,8]],axis=-1)       

array([[0, 2, 3],
       [5, 7, 8]])

# WAP to print all items from max number in list

In [31]:
x = [16,17,2,5,7]

x= np.array(x)
y = x.argmax()  # argmax() gives index no of max number.

for i in range(y,len(x)):
    print(x[i],end=' ')

17 2 5 7 

# replacing any item in any array using indexing

In [32]:
array = np.array([16,17,2,5,7])
array[1]=100
array

array([ 16, 100,   2,   5,   7])

In [33]:
array = np.array([[21,16,17],
                  [2,5,3],
                  [7,0,8]])
array[0][0]=100
array

array([[100,  16,  17],
       [  2,   5,   3],
       [  7,   0,   8]])

In [34]:
array = np.array([[21,16,17],
                  [2,5,3],
                  [7,0,8]])

array[0:2,0:2]=[[100,200],[300,400]]
array

array([[100, 200,  17],
       [300, 400,   3],
       [  7,   0,   8]])

# Inserting item into Array

In [44]:
a = np.array([16,17,2,5,7])
print(np.insert(a,1,100))
print()
print(np.insert(a,-1,100))
print()
print(np.insert(a,len(a),100))
print()
print(np.insert(a,6,100))

[ 16 100  17   2   5   7]

[ 16  17   2   5 100   7]

[ 16  17   2   5   7 100]



IndexError: index 6 is out of bounds for axis 0 with size 5

In [45]:
a = np.array([[21,16,17],
                  [2,5,3],
                  [7,0,8]])
print(np.insert(a,[0][0],100))

[100  21  16  17   2   5   3   7   0   8]


# Append()

In [46]:
a = np.array([5,6,7,8])
a

array([5, 6, 7, 8])

In [47]:
np.append(a,10)

array([ 5,  6,  7,  8, 10])

In [48]:
print(np.append(a,(10,20)))
print(np.append(a,[10,20]))

[ 5  6  7  8 10 20]
[ 5  6  7  8 10 20]


In [49]:
array1 = np.array([2,3,4])
array2 = np.array([5,3,4])

array3 = np.append(array1,array2)
array3

array([2, 3, 4, 5, 3, 4])

In [50]:
array1 = np.array([[2,3,4],
                   [5,6,7]])

array2 = np.array([5,3,4])

np.append(array1,array2)

array([2, 3, 4, 5, 6, 7, 5, 3, 4])

## Appending row wise in matrix

In [53]:
array1 = np.array([[2,3,4],
                   [5,6,7]])

array2 = np.array([[5,3,2]])   # 3 columns must because array1 has 3 columns

np.append(array1,array2,axis=0)

array([[2, 3, 4],
       [5, 6, 7],
       [5, 3, 2]])

In [54]:
array1 = np.array([[2,3,4],
                   [5,6,7]])

array2 = np.array([[5,3,4],
                   [0,0,0]])

np.append(array1,array2,axis=0)

array([[2, 3, 4],
       [5, 6, 7],
       [5, 3, 4],
       [0, 0, 0]])

## Appending column wise in matrix

In [55]:
array1 = np.array([[2,3,4],
                   [5,6,7]])

array2 = np.array([[5],
                   [0]])

np.append(array1,array2,axis=1)

array([[2, 3, 4, 5],
       [5, 6, 7, 0]])

# Concatenate() arrays

## concatenates the arrays alongside the axis

In [56]:
array1 = np.array([2,3,4])
array2 = np.array([5,3,4])
array3 = np.array([5,3,9])

final_array = np.concatenate([array1,array2,array3])  # by using append we can contatinate max 2 arrays!
final_array

array([2, 3, 4, 5, 3, 4, 5, 3, 9])

In [57]:
array1 = np.array([2,3,4])
array2 = np.array([5,3,4])
array3 = np.array([5,3,9])


final_array = np.concatenate([array1,array2,array3])
final_array.reshape(3,3)

array([[2, 3, 4],
       [5, 3, 4],
       [5, 3, 9]])

## Concatenation along rows in matrix

In [61]:
array1 = np.array([[2,3,4],
                   [5,6,7]])

array2 = np.array([[5,8,9]])

np.concatenate([array1,array2],axis=0)

array([[2, 3, 4],
       [5, 6, 7],
       [5, 8, 9]])

## Concatenation along columns in matrix

In [63]:
array1 = np.array([[2,3,4],
                   [5,6,7]])

array2 = np.array([[5],
                   [0]])

np.concatenate([array1,array2],axis=1)

array([[2, 3, 4, 5],
       [5, 6, 7, 0]])

# Looping on array

In [64]:
array1 = np.array([2,3,4,6,7])
for i in array1:
    print(i)

2
3
4
6
7


In [65]:
array1 = np.array([[2,3,4,6,7]])
for i in array1:
    print(i)

[2 3 4 6 7]


In [66]:
array1 = np.array([2,3,4,6,7])
for i,j in enumerate(array1):
    print(i,j)

0 2
1 3
2 4
3 6
4 7


In [67]:
RRR = np.array([[2, 3, 4],
       [5, 6, 7],
       [5, 8, 9],
       [0, 0, 0]])

for i in RRR:
    print(i)
    
print()
for i,v in enumerate(RRR):
    print(i,v)

[2 3 4]
[5 6 7]
[5 8 9]
[0 0 0]

0 [2 3 4]
1 [5 6 7]
2 [5 8 9]
3 [0 0 0]


## np.nditer()

In [68]:
import numpy as np

RRR = np.array([[2, 3, 4],
       [5, 6, 7],
       [5, 8, 9],
       [0, 0, 0]])

for i in np.nditer(RRR):
    print(i,end=' ')

2 3 4 5 6 7 5 8 9 0 0 0 

In [69]:
for i in (RRR):
    for j in range(len(i)):
        print(i[j],end=' ')

2 3 4 5 6 7 5 8 9 0 0 0 

##   np.ndenumerate()

In [70]:
display(RRR)
for i,v in np.ndenumerate(RRR):
    print(i,v)                         # 0 row 1 column pe 3 value present hai.

array([[2, 3, 4],
       [5, 6, 7],
       [5, 8, 9],
       [0, 0, 0]])

(0, 0) 2
(0, 1) 3
(0, 2) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(2, 0) 5
(2, 1) 8
(2, 2) 9
(3, 0) 0
(3, 1) 0
(3, 2) 0


# Ceil

In [71]:
import numpy as np

In [72]:
a = 2.4
np.ceil(a)

3.0

In [73]:
a = 2.6
np.ceil(a)

3.0

In [74]:
a = -2.46
np.ceil(a)

-2.0

# floor

In [75]:
a=2.6
np.floor(a)

2.0

In [76]:
a=-2.4
np.floor(a)

-3.0

#  around()

In [ ]:
works exactly in same way as that of round function only difference is 
1) around() do not change datatype of number
2) around() function can be used for an array.

In [77]:
# round function

round(2.4) , round(2.6) , round(2.5)

(2, 3, 2)

In [78]:
# round function

round(2.4846,2) , round(2.54844,2)

(2.48, 2.55)

In [79]:
np.around(2.4) , np.around(2.6) , np.around(2.5)   # note that output is also in float unlike round function 

(2.0, 3.0, 2.0)

In [80]:
np.around(2.4846,2) , np.round(2.54844,2)

(2.48, 2.55)

In [81]:
a = np.array([[-2.46,7.8],
              [5.67,-2.57]])
np.around(a)

array([[-2.,  8.],
       [ 6., -3.]])

In [82]:
a = np.array([[-2.46678,7.85687],
              [5.671224,-2.5778970]])
np.around(a,2)

array([[-2.47,  7.86],
       [ 5.67, -2.58]])

# copy

In [84]:
array1 = np.array([2,4,6,8])
array2 = np.copy(array1)

array2[0]=0
print(array2,array1)

[0 4 6 8] [2 4 6 8]


In [85]:
array1 = np.array([[2,4],[6,8]])
array2 = array1.copy()

array1[0][0]=0
print(array2)
print()
print(array1)

[[2 4]
 [6 8]]

[[0 4]
 [6 8]]


# np.where (very imp)

In [2]:
import numpy as np

In [4]:
arr = np.array([4,5,6,2,3])    # 5,6 are greater than 4 hence we get index no of 5 and 6 as output.
a = np.where(arr>4)

In [5]:
a

(array([1, 2], dtype=int64),)

In [8]:
a[0]

array([1, 2], dtype=int64)

In [87]:
arr = np.array([4,5,6,2,3,4])
np.where(arr==1)                    # 1 is not present hence empty output

(array([], dtype=int64),)

In [88]:
l1 = [4,5,6,2,3,4]
[index for index,value in enumerate(l1) if value < 6]

[0, 1, 3, 4, 5]

In [89]:
arr = np.array([4,5,6,2,3,4])         # only 5,3 is odd.
np.where(arr%2==1)

(array([1, 4], dtype=int64),)

## use of np.where to replace the values that does not meet the given condition in array

In [91]:
arr = np.array([4,5,6,2,3,4])
arr=np.where(arr%2==1,arr,100)
arr

array([100,   5, 100, 100,   3, 100])

In [92]:
arr = np.array([4,5,6,2,3,4])
arr=np.where(arr<arr[0],arr,np.inf)
arr

array([inf, inf, inf,  2.,  3., inf])

In [93]:
arr = np.array([4,5,6,2,3,4])
arr=np.where(arr<arr[0],arr,0)
arr

array([0, 0, 0, 2, 3, 0])

# arg


### argmax >> returns the index of the maximum number in the array

In [94]:
A = [2,3,6,9,1]

np.argmax(A)

3

### argmin >> returns the index of the minimum number in the array

In [95]:
A = [2,3,6,9,1]

np.argmin(A)

4

###  argsort >> returns the indexes of the sorted array


In [96]:
A = [2,3,6,9,1]

np.argsort(A)

array([4, 0, 1, 2, 3], dtype=int64)

# size

In [97]:
A = [2,3,6,9,1]
np.size(A)

5

In [98]:
B = [[2,3,4],[5,6,6]]
np.size(B)

6

# aggregate functions

In [99]:
a = [2,3,6,9,1]
print(min(a))
print(max(a))
print(sum(a))

1
9
21


In [100]:
A = [1,2,4,5]
print(np.mean(A))
print(np.median(A))
print(np.std(A))
print(np.var(A))

3.0
3.0
1.5811388300841898
2.5


# mathematical operations on Array

In [101]:
array = np.array([2,3,6,9,1,2])
array

array([2, 3, 6, 9, 1, 2])

In [102]:
array1 = np.array([2,3,6,9,1,2])
array2 = np.array([0,1,6,2,3,6])

array1+array2

array([ 2,  4, 12, 11,  4,  8])

In [ ]:
addiion,subtraction,sq,mul,div,floor div,remainder

In [103]:
array 

array([2, 3, 6, 9, 1, 2])

In [104]:
array +10

array([12, 13, 16, 19, 11, 12])

In [105]:
# list addition is different from array addition.

[2,3,4]+[10] 

[2, 3, 4, 10]

# matrix dot product

In [106]:
arr1 = np.array([[3,4],
                 [5,8]])

arr2 = np.array([[7,6],
                 [9,0]])

np.dot(arr1,arr2)

# 3*7+4*9    3*6+4*0
# 5*7+8*9    5*6+8*0

array([[ 57,  18],
       [107,  30]])

In [107]:
arr1 = np.array([[3,4],
                 [5,5],
                 [0,1]])

arr2 = np.array([[4,6,1],
                 [9,0,2]])

np.dot(arr1,arr2)

array([[48, 18, 11],
       [65, 30, 15],
       [ 9,  0,  2]])

In [108]:
arr1 = np.array([[3,4],
                 [5,5],
                 [0,1]])

arr2 = np.array([[4,6],
                 [9,0]])

np.dot(arr2,arr1)         

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

# log function

In [109]:
np.log(np.exp(1))   # Natural log is set to base e

1.0

In [110]:
np.log(1)

0.0

In [111]:
np.log(2.718281828459045)       # value of e is 2.718281828459045

1.0

In [112]:
np.log10(1)    # here base is 10

0.0

In [113]:
np.log10(10)

1.0

In [114]:
np.log10(100)

2.0

In [115]:
np.log2(2)

1.0

In [116]:
np.log2(1)

0.0

# Trignometry

In [ ]:
np.degres()             --- gives answer in degrees
np.sin(),np.cos() etc.  --- gives answer in radian 


In [117]:
np.pi

3.141592653589793

In [118]:
# np.sin(radian value)

np.sin(np.pi/6)

0.49999999999999994

In [119]:
np.sin(np.deg2rad(30))  # np.deg2rad(30) converts 30 degree to radian

0.49999999999999994

In [120]:
np.sin(np.radians(30))  #  np.radians(30) converts 30 degree to radian

0.49999999999999994

In [121]:
np.degrees(np.pi/6)  # we get answer in degrees.

29.999999999999996

In [122]:
np.degrees(np.deg2rad(30)) # we get answer in degrees.

29.999999999999996

In [123]:
np.rad2deg(np.pi/6) # we get answer in degrees.

29.999999999999996

In [124]:
angle = 120
adj = 10
opp = ?   ans. -17.3205

SyntaxError: invalid syntax (2332914769.py, line 3)

In [125]:
np.tan(np.radians(120))*10     

-17.32050807568878